<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Vagas\Vaga;
use Illuminate\Database\Seeder;

class VagasSeeder extends Seeder
{
    public function run(): void
    {
        $coordenador = User::where('perfil', 'coordenador')->first();
        $gestor      = User::where('perfil', 'gestor')->first();

        $vagas = [
            // --- ESTÁGIOS PRESENCIAIS ---
            [
                'titulo'               => 'Estágio em Desenvolvimento de Software',
                'descricao'            => 'Desenvolvimento de sistemas web e APIs RESTful utilizando PHP e Laravel. O estagiário participará de todo o ciclo de desenvolvimento, desde o levantamento de requisitos até a entrega em produção.',
                'requisitos'           => 'Cursando Ciência da Computação, Sistemas de Informação ou áreas afins a partir do 4º semestre. Conhecimento básico em PHP, HTML, CSS e JavaScript.',
                'requisitos_desejaveis'=> 'Experiência com Laravel ou outro framework MVC. Conhecimento em Git e metodologias ágeis.',
                'beneficios'           => 'Vale-transporte, vale-refeição, auxílio-educação e seguro de vida.',
                'tipo'                 => 'estagio',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Sistemas de Informação', 'Análise e Desenvolvimento de Sistemas'],
                'remuneracao'          => 1200.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(30)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Sistema de Gestão Interna',
                'projeto_codigo'       => 'TI-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Análise de Dados',
                'descricao'            => 'Suporte à equipe de Business Intelligence na construção de dashboards, extração e tratamento de dados para apoio à tomada de decisão institucional.',
                'requisitos'           => 'Cursando Estatística, Matemática, Ciência da Computação ou Sistemas de Informação. Conhecimento em Excel avançado e SQL básico.',
                'requisitos_desejaveis'=> 'Experiência com Power BI, Python (pandas) ou R.',
                'beneficios'           => 'Vale-transporte, vale-alimentação e acesso a plataformas de cursos online.',
                'tipo'                 => 'estagio',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Estatística', 'Ciência da Computação', 'Matemática'],
                'remuneracao'          => 1100.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(20)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'BI Institucional',
                'projeto_codigo'       => 'TI-2026-002',
            ],
            [
                'titulo'               => 'Estágio em Administração',
                'descricao'            => 'Suporte administrativo ao setor de recursos humanos, incluindo controle de documentos, agendamentos, atendimento ao colaborador e apoio em processos seletivos.',
                'requisitos'           => 'Cursando Administração a partir do 3º semestre. Boa comunicação verbal e escrita, conhecimento em pacote Office.',
                'requisitos_desejaveis'=> 'Experiência com sistemas de RH ou ERP. Facilidade com atendimento ao público.',
                'beneficios'           => 'Vale-transporte e vale-refeição.',
                'tipo'                 => 'estagio',
                'area'                 => 'Administração',
                'curso_desejado'       => ['Administração'],
                'remuneracao'          => 900.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(15)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Modernização RH',
                'projeto_codigo'       => 'ADM-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Contabilidade',
                'descricao'            => 'Apoio ao setor contábil na conciliação bancária, lançamentos fiscais, elaboração de relatórios financeiros e controle de obrigações acessórias.',
                'requisitos'           => 'Cursando Ciências Contábeis a partir do 4º semestre. Noções de contabilidade geral e legislação fiscal.',
                'requisitos_desejaveis'=> 'Conhecimento em SPED, NFe ou algum sistema contábil (Totvs, Domínio, etc.).',
                'beneficios'           => 'Vale-transporte, vale-refeição e participação em treinamentos internos.',
                'tipo'                 => 'estagio',
                'area'                 => 'Contabilidade',
                'curso_desejado'       => ['Ciências Contábeis'],
                'remuneracao'          => 1000.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(25)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Gestão Fiscal 2026',
                'projeto_codigo'       => 'CONT-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Comunicação e Marketing',
                'descricao'            => 'Produção de conteúdo para redes sociais, apoio em eventos institucionais, criação de peças gráficas e redação de releases para a assessoria de imprensa.',
                'requisitos'           => 'Cursando Comunicação Social, Jornalismo ou Publicidade e Propaganda. Boa redação e criatividade.',
                'requisitos_desejaveis'=> 'Domínio em Canva, Adobe Photoshop ou Illustrator. Experiência com gestão de redes sociais.',
                'beneficios'           => 'Vale-transporte e vale-refeição.',
                'tipo'                 => 'estagio',
                'area'                 => 'Comunicação',
                'curso_desejado'       => ['Comunicação Social', 'Jornalismo', 'Publicidade e Propaganda'],
                'remuneracao'          => 900.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(10)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Comunicação Institucional 2026',
                'projeto_codigo'       => 'COM-2026-001',
            ],

            // --- ESTÁGIOS REMOTOS ---
            [
                'titulo'               => 'Estágio em Desenvolvimento Front-end (Remoto)',
                'descricao'            => 'Desenvolvimento e manutenção de interfaces web utilizando React.js. Colaboração em equipe multidisciplinar para entrega de soluções digitais responsivas e acessíveis.',
                'requisitos'           => 'Cursando Ciência da Computação, Sistemas de Informação ou Engenharia de Software a partir do 3º semestre. Conhecimento em HTML, CSS e JavaScript.',
                'requisitos_desejaveis'=> 'Experiência com React, Vue ou Angular. Conhecimento em design responsivo e acessibilidade web.',
                'beneficios'           => 'Ajuda de custo para internet e equipamento.',
                'tipo'                 => 'estagio',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Sistemas de Informação', 'Engenharia de Software'],
                'remuneracao'          => 1300.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'remoto',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(45)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Portal do Estudante',
                'projeto_codigo'       => 'TI-2026-003',
            ],
            [
                'titulo'               => 'Estágio em Psicologia Organizacional (Remoto)',
                'descricao'            => 'Apoio ao setor de gestão de pessoas em processos seletivos online, aplicação de testes psicológicos, entrevistas por vídeo e elaboração de laudos.',
                'requisitos'           => 'Cursando Psicologia a partir do 6º semestre. Interesse na área organizacional.',
                'requisitos_desejaveis'=> 'Conhecimento em testes psicológicos (BPR-5, Palográfico, MBTI). Experiência com entrevistas por competência.',
                'beneficios'           => 'Supervisão psicológica inclusa e acesso a plataformas de avaliação.',
                'tipo'                 => 'estagio',
                'area'                 => 'Psicologia',
                'curso_desejado'       => ['Psicologia'],
                'remuneracao'          => 1000.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'remoto',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(35)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Programa de Seleção Digital',
                'projeto_codigo'       => 'PSI-2026-001',
            ],

            // --- ESTÁGIOS HÍBRIDOS ---
            [
                'titulo'               => 'Estágio em Engenharia Civil',
                'descricao'            => 'Acompanhamento de obras e projetos de infraestrutura, elaboração de relatórios técnicos, levantamento de quantitativos e suporte ao engenheiro responsável.',
                'requisitos'           => 'Cursando Engenharia Civil a partir do 5º semestre. Conhecimento básico em AutoCAD.',
                'requisitos_desejaveis'=> 'Experiência com Revit, Excel para orçamentação e normas da ABNT.',
                'beneficios'           => 'Vale-transporte, vale-refeição e EPI fornecidos.',
                'tipo'                 => 'estagio',
                'area'                 => 'Engenharia',
                'curso_desejado'       => ['Engenharia Civil'],
                'remuneracao'          => 1500.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'hibrido',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(40)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Infraestrutura Campus UFSC',
                'projeto_codigo'       => 'ENG-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Design Gráfico',
                'descricao'            => 'Criação de materiais visuais para comunicação interna e externa, desenvolvimento de identidade visual para projetos e suporte em produção editorial.',
                'requisitos'           => 'Cursando Design Gráfico ou Design Visual. Portfólio obrigatório.',
                'requisitos_desejaveis'=> 'Experiência com Adobe Creative Suite (Photoshop, Illustrator, InDesign). Conhecimento em motion design.',
                'beneficios'           => 'Vale-transporte e acesso a licenças Adobe.',
                'tipo'                 => 'estagio',
                'area'                 => 'Design',
                'curso_desejado'       => ['Design Gráfico', 'Design Visual'],
                'remuneracao'          => 1100.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(22)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Identidade Visual 2026',
                'projeto_codigo'       => 'DES-2026-001',
            ],

            // --- EMPREGOS CLT PRESENCIAIS ---
            [
                'titulo'               => 'Analista de Sistemas Pleno',
                'descricao'            => 'Desenvolvimento e manutenção de sistemas legados e novos projetos em PHP/Laravel. Responsável por análise de requisitos, arquitetura de soluções e code review.',
                'requisitos'           => 'Graduação em Ciência da Computação, Sistemas de Informação ou áreas afins. Mínimo 3 anos de experiência com PHP e bancos de dados relacionais.',
                'requisitos_desejaveis'=> 'Experiência com microsserviços, Docker, CI/CD e metodologias ágeis (Scrum/Kanban).',
                'beneficios'           => 'Plano de saúde, plano odontológico, vale-refeição, vale-transporte, PLR e plano de carreira.',
                'tipo'                 => 'emprego',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Sistemas de Informação', 'Engenharia de Software'],
                'remuneracao'          => 5500.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(30)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Modernização Tecnológica',
                'projeto_codigo'       => 'TI-2026-010',
            ],
            [
                'titulo'               => 'Contador Sênior',
                'descricao'            => 'Responsável pela gestão contábil e fiscal da organização, elaboração de demonstrações financeiras, atendimento a auditorias e conformidade com a legislação vigente.',
                'requisitos'           => 'Graduação em Ciências Contábeis e CRC ativo. Mínimo 5 anos de experiência em contabilidade pública ou do terceiro setor.',
                'requisitos_desejaveis'=> 'Especialização em contabilidade pública. Conhecimento em Siafi, SPED e NBC TG.',
                'beneficios'           => 'Plano de saúde, vale-refeição, vale-transporte e 13º salário.',
                'tipo'                 => 'emprego',
                'area'                 => 'Contabilidade',
                'curso_desejado'       => ['Ciências Contábeis'],
                'remuneracao'          => 6500.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(20)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Conformidade Contábil 2026',
                'projeto_codigo'       => 'CONT-2026-010',
            ],
            [
                'titulo'               => 'Assistente Administrativo',
                'descricao'            => 'Suporte às atividades administrativas do setor, controle de documentos, agendamentos, atendimento telefônico e presencial, e apoio à gestão de contratos.',
                'requisitos'           => 'Ensino médio completo ou cursando graduação em Administração. Boa comunicação e organização.',
                'requisitos_desejaveis'=> 'Experiência anterior em funções administrativas. Conhecimento em sistemas ERP.',
                'beneficios'           => 'Vale-transporte, vale-refeição e plano de saúde.',
                'tipo'                 => 'emprego',
                'area'                 => 'Administração',
                'curso_desejado'       => ['Administração', 'Secretariado Executivo'],
                'remuneracao'          => 2200.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(18)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => null,
                'projeto_codigo'       => null,
            ],
            [
                'titulo'               => 'Engenheiro Civil Júnior',
                'descricao'            => 'Elaboração de projetos estruturais, acompanhamento de obras, fiscalização de serviços e elaboração de relatórios técnicos para projetos de pesquisa e extensão.',
                'requisitos'           => 'Graduação em Engenharia Civil e CREA ativo. Disponibilidade para visitas técnicas.',
                'requisitos_desejaveis'=> 'Experiência com BIM (Revit). Conhecimento em gestão de projetos (PMBok).',
                'beneficios'           => 'Plano de saúde, vale-refeição, vale-transporte e auxílio combustível.',
                'tipo'                 => 'emprego',
                'area'                 => 'Engenharia',
                'curso_desejado'       => ['Engenharia Civil'],
                'remuneracao'          => 4500.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(28)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Laboratório de Construção',
                'projeto_codigo'       => 'ENG-2026-010',
            ],

            // --- EMPREGOS CLT REMOTOS ---
            [
                'titulo'               => 'Desenvolvedor Back-end Pleno (Remoto)',
                'descricao'            => 'Desenvolvimento de APIs RESTful e serviços de integração. Participação em decisões de arquitetura e revisão de código da equipe.',
                'requisitos'           => 'Graduação em área de TI. Experiência sólida com Node.js ou Python e bancos de dados NoSQL.',
                'requisitos_desejaveis'=> 'Experiência com AWS, Kubernetes e práticas de DevSecOps.',
                'beneficios'           => 'Plano de saúde, auxílio-internet, auxílio home office e stock options.',
                'tipo'                 => 'emprego',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Sistemas de Informação', 'Engenharia de Software'],
                'remuneracao'          => 7000.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'remoto',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(50)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Plataforma Digital FAPEU',
                'projeto_codigo'       => 'TI-2026-020',
            ],
            [
                'titulo'               => 'Analista de Marketing Digital (Remoto)',
                'descricao'            => 'Gestão de campanhas digitais (Google Ads, Meta Ads), SEO, análise de métricas e produção de relatórios de performance para os projetos da fundação.',
                'requisitos'           => 'Graduação em Publicidade, Marketing ou Comunicação. Experiência com ferramentas de mídia paga.',
                'requisitos_desejaveis'=> 'Certificações Google e Meta. Experiência com HubSpot ou RD Station.',
                'beneficios'           => 'Plano de saúde, auxílio-internet e bônus por performance.',
                'tipo'                 => 'emprego',
                'area'                 => 'Comunicação',
                'curso_desejado'       => ['Publicidade e Propaganda', 'Comunicação Social'],
                'remuneracao'          => 4200.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'remoto',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(33)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Presença Digital 2026',
                'projeto_codigo'       => 'COM-2026-010',
            ],

            // --- EMPREGOS CLT HÍBRIDOS ---
            [
                'titulo'               => 'Analista de Recursos Humanos',
                'descricao'            => 'Gestão do ciclo completo de RH: recrutamento e seleção, treinamento e desenvolvimento, gestão de desempenho e administração de pessoal.',
                'requisitos'           => 'Graduação em Administração, Psicologia ou Gestão de RH. Mínimo 2 anos de experiência em RH generalista.',
                'requisitos_desejaveis'=> 'MBA em Gestão de Pessoas. Conhecimento em legislação trabalhista e sistemas de folha de pagamento.',
                'beneficios'           => 'Plano de saúde, plano odontológico, vale-refeição e vale-transporte.',
                'tipo'                 => 'emprego',
                'area'                 => 'Administração',
                'curso_desejado'       => ['Administração', 'Psicologia', 'Gestão de Recursos Humanos'],
                'remuneracao'          => 4000.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'hibrido',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(14)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => null,
                'projeto_codigo'       => null,
            ],
            [
                'titulo'               => 'Gestor de Projetos (PMO)',
                'descricao'            => 'Coordenação de projetos de pesquisa e inovação, elaboração de cronogramas, controle orçamentário, gestão de stakeholders e elaboração de relatórios para agências de fomento.',
                'requisitos'           => 'Graduação em qualquer área. Certificação PMP ou equivalente. Experiência em gestão de projetos científicos ou tecnológicos.',
                'requisitos_desejaveis'=> 'Experiência com agências de fomento (FINEP, CNPq, CAPES). Inglês avançado.',
                'beneficios'           => 'Plano de saúde, vale-refeição, vale-transporte e PLR.',
                'tipo'                 => 'emprego',
                'area'                 => 'Administração',
                'curso_desejado'       => ['Administração', 'Ciência da Computação', 'Engenharia de Produção'],
                'remuneracao'          => 8000.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'hibrido',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(60)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Escritório de Projetos FAPEU',
                'projeto_codigo'       => 'PMO-2026-001',
            ],

            // --- BOLSAS ---
            [
                'titulo'               => 'Bolsista de Pesquisa em Biotecnologia',
                'descricao'            => 'Desenvolvimento de atividades de pesquisa científica no Laboratório de Biotecnologia Molecular, envolvendo técnicas de biologia molecular, cultura de células e análise de dados experimentais.',
                'requisitos'           => 'Graduando em Biologia, Farmácia, Química ou Biomedicina a partir do 5º semestre. Disponibilidade de 20h semanais.',
                'requisitos_desejaveis'=> 'Experiência prévia em laboratório. Conhecimento em técnicas de PCR, eletroforese e espectrofotometria.',
                'beneficios'           => 'Bolsa CNPq nível IC, experiência em pesquisa e acesso a laboratórios de ponta.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Ciências Biológicas',
                'curso_desejado'       => ['Biologia', 'Farmácia', 'Química', 'Biomedicina'],
                'remuneracao'          => 700.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-970',
                'logradouro'           => 'Campus Universitário Reitor João David Ferreira Lima',
                'numero'               => 's/n',
                'bairro'               => 'Trindade',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(15)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Pesquisa em Biotecnologia Aplicada',
                'projeto_codigo'       => 'BIO-2026-001',
            ],
            [
                'titulo'               => 'Bolsista em Desenvolvimento de Software Científico',
                'descricao'            => 'Desenvolvimento de ferramentas computacionais para análise de grandes volumes de dados gerados em experimentos científicos. Trabalho em equipe interdisciplinar de pesquisa.',
                'requisitos'           => 'Graduando em Ciência da Computação, Física ou Matemática. Programação em Python ou C++.',
                'requisitos_desejaveis'=> 'Conhecimento em computação científica (NumPy, SciPy, CUDA). Experiência com Git e documentação técnica.',
                'beneficios'           => 'Bolsa de pesquisa e participação em publicações científicas.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Física', 'Matemática'],
                'remuneracao'          => 800.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(18)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Computação Científica Avançada',
                'projeto_codigo'       => 'TI-2026-050',
            ],
            [
                'titulo'               => 'Bolsista em Pesquisa Jurídica',
                'descricao'            => 'Pesquisa e análise de legislação, jurisprudência e doutrina aplicadas ao terceiro setor e à gestão de fundações de apoio. Elaboração de pareceres e notas técnicas.',
                'requisitos'           => 'Cursando Direito a partir do 6º semestre. Interesse em direito administrativo e do terceiro setor.',
                'requisitos_desejaveis'=> 'Participação em grupos de pesquisa ou iniciação científica. Conhecimento em bases de dados jurídicas (LexML, JusBrasil).',
                'beneficios'           => 'Bolsa de pesquisa e acompanhamento de profissional sênior da área jurídica.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Direito',
                'curso_desejado'       => ['Direito'],
                'remuneracao'          => 750.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cep'                  => '88040-400',
                'logradouro'           => 'Av. Madre Benvenuta',
                'numero'               => '2007',
                'bairro'               => 'Santa Mônica',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(12)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Conformidade Legal FAPEU',
                'projeto_codigo'       => 'JUR-2026-001',
            ],
            [
                'titulo'               => 'Bolsista em Educação Ambiental',
                'descricao'            => 'Apoio a projeto de extensão universitária com foco em educação ambiental em escolas públicas da região. Elaboração de materiais didáticos e realização de oficinas.',
                'requisitos'           => 'Cursando Pedagogia, Biologia, Geografia ou Ciências Ambientais. Interesse em extensão universitária.',
                'requisitos_desejaveis'=> 'Experiência em docência ou monitoria. Habilidade com criação de materiais educativos.',
                'beneficios'           => 'Bolsa de extensão e certificado de participação.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Educação',
                'curso_desejado'       => ['Pedagogia', 'Biologia', 'Geografia'],
                'remuneracao'          => 600.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(8)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Extensão Ambiental Escolar',
                'projeto_codigo'       => 'EDU-2026-001',
            ],

            // --- VAGAS COM STATUS VARIADOS (para testar filtros) ---
            [
                'titulo'               => 'Estágio em Enfermagem',
                'descricao'            => 'Atividades práticas supervisionadas em unidade hospitalar conveniada, desenvolvimento de habilidades clínicas e participação em projetos de saúde coletiva.',
                'requisitos'           => 'Cursando Enfermagem a partir do 6º semestre. Disponibilidade para plantões.',
                'requisitos_desejaveis'=> 'Experiência em primeiros socorros e BLS.',
                'beneficios'           => 'Vale-transporte e uniforme fornecido.',
                'tipo'                 => 'estagio',
                'area'                 => 'Saúde',
                'curso_desejado'       => ['Enfermagem'],
                'remuneracao'          => 850.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->subDays(5)->toDateString(),
                'status'               => 'encerrada',
                'projeto_nome'         => 'Saúde Coletiva UFSC',
                'projeto_codigo'       => 'SAU-2026-001',
            ],
            [
                'titulo'               => 'Analista de Segurança da Informação',
                'descricao'            => 'Monitoramento de incidentes, análise de vulnerabilidades, implementação de políticas de segurança e resposta a incidentes de segurança cibernética.',
                'requisitos'           => 'Graduação em TI. Certificação CompTIA Security+ ou equivalente.',
                'requisitos_desejaveis'=> 'Certificação CISSP, CEH ou OSCP. Experiência com SIEM e análise forense.',
                'beneficios'           => 'Plano de saúde, vale-refeição e bônus anual.',
                'tipo'                 => 'emprego',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Redes de Computadores'],
                'remuneracao'          => 9000.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(45)->toDateString(),
                'status'               => 'aguardando_autorizacao',
                'projeto_nome'         => 'Segurança Cibernética FAPEU',
                'projeto_codigo'       => 'TI-2026-030',
            ],
            [
                'titulo'               => 'Estágio em Farmácia Hospitalar',
                'descricao'            => 'Atividades de farmácia clínica em hospital universitário, participação em rounds médicos, seguimento farmacoterapêutico e atenção farmacêutica ao paciente.',
                'requisitos'           => 'Cursando Farmácia a partir do 8º semestre. CRF provisório.',
                'requisitos_desejaveis'=> 'Interesse em farmácia clínica e hospitalar.',
                'beneficios'           => 'Vale-transporte e certificado.',
                'tipo'                 => 'estagio',
                'area'                 => 'Saúde',
                'curso_desejado'       => ['Farmácia'],
                'remuneracao'          => 950.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(20)->toDateString(),
                'status'               => 'rascunho',
                'projeto_nome'         => 'Farmácia Clínica HU',
                'projeto_codigo'       => 'SAU-2026-010',
            ],
            [
                'titulo'               => 'Técnico em Infraestrutura de TI',
                'descricao'            => 'Suporte técnico de nível 2, manutenção de servidores, gerenciamento de redes LAN/WAN e suporte a usuários internos.',
                'requisitos'           => 'Técnico ou graduando em Redes ou TI. Experiência com Windows Server e Active Directory.',
                'requisitos_desejaveis'=> 'Certificação MCSA ou CompTIA Network+.',
                'beneficios'           => 'Vale-transporte, vale-refeição e plano de saúde.',
                'tipo'                 => 'emprego',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Redes de Computadores', 'Análise e Desenvolvimento de Sistemas'],
                'remuneracao'          => 3200.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->subDays(10)->toDateString(),
                'status'               => 'inativa',
                'projeto_nome'         => null,
                'projeto_codigo'       => null,
            ],

            // --- VAGAS SEMELHANTES (para testar busca por similaridade) ---
            [
                'titulo'               => 'Estágio em Desenvolvimento Web Full-stack',
                'descricao'            => 'Atuação no desenvolvimento de aplicações web completas, desde o banco de dados até a interface do usuário, utilizando stack PHP/Laravel + Vue.js.',
                'requisitos'           => 'Cursando Ciência da Computação, Sistemas de Informação ou Engenharia de Software. Conhecimento em PHP e JavaScript.',
                'requisitos_desejaveis'=> 'Experiência com Vue.js, TailwindCSS e Docker.',
                'beneficios'           => 'Vale-transporte, vale-refeição e flexibilidade de horário.',
                'tipo'                 => 'estagio',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Sistemas de Informação'],
                'remuneracao'          => 1400.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(38)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Portal de Serviços',
                'projeto_codigo'       => 'TI-2026-004',
            ],
            [
                'titulo'               => 'Estágio em Programação Back-end',
                'descricao'            => 'Desenvolvimento de microsserviços e integrações entre sistemas, com foco em performance e escalabilidade. Trabalho com equipe de engenharia de software.',
                'requisitos'           => 'Cursando Ciência da Computação ou Engenharia de Software a partir do 5º semestre. Conhecimento em Java ou Python.',
                'requisitos_desejaveis'=> 'Experiência com Spring Boot, FastAPI ou Django. Noções de mensageria (RabbitMQ, Kafka).',
                'beneficios'           => 'Vale-transporte, vale-alimentação e mentorias técnicas.',
                'tipo'                 => 'estagio',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Ciência da Computação', 'Engenharia de Software'],
                'remuneracao'          => 1350.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'remoto',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(42)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Integração de Sistemas',
                'projeto_codigo'       => 'TI-2026-005',
            ],
            [
                'titulo'               => 'Estágio em Suporte e Infraestrutura de TI',
                'descricao'            => 'Atendimento a chamados de suporte técnico, configuração de estações de trabalho, instalação de softwares e suporte presencial aos usuários da organização.',
                'requisitos'           => 'Cursando Redes de Computadores ou Análise e Desenvolvimento de Sistemas. Conhecimento em Windows e redes básicas.',
                'requisitos_desejaveis'=> 'Experiência com suporte técnico. Conhecimento em Linux.',
                'beneficios'           => 'Vale-transporte e vale-alimentação.',
                'tipo'                 => 'estagio',
                'area'                 => 'Tecnologia da Informação',
                'curso_desejado'       => ['Redes de Computadores', 'Análise e Desenvolvimento de Sistemas'],
                'remuneracao'          => 950.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(16)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => null,
                'projeto_codigo'       => null,
            ],
            [
                'titulo'               => 'Bolsista em Pesquisa em Educação',
                'descricao'            => 'Participação em projeto de pesquisa sobre práticas pedagógicas inovadoras no ensino superior, coleta e análise de dados qualitativos e quantitativos.',
                'requisitos'           => 'Cursando Pedagogia ou Licenciaturas a partir do 4º semestre. Interesse em pesquisa educacional.',
                'requisitos_desejaveis'=> 'Conhecimento em metodologia científica e análise estatística básica.',
                'beneficios'           => 'Bolsa de pesquisa e co-autoria em publicações.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Educação',
                'curso_desejado'       => ['Pedagogia', 'Letras', 'História'],
                'remuneracao'          => 700.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'remoto',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(25)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Inovação no Ensino Superior',
                'projeto_codigo'       => 'EDU-2026-010',
            ],
            [
                'titulo'               => 'Bolsista em Pesquisa Socioeconômica',
                'descricao'            => 'Apoio a levantamentos socioeconômicos em comunidades, tabulação e análise de dados estatísticos, elaboração de relatórios e apresentação de resultados.',
                'requisitos'           => 'Cursando Ciências Econômicas, Ciências Sociais ou Estatística. Domínio de Excel ou SPSS.',
                'requisitos_desejaveis'=> 'Conhecimento em STATA, R ou Python para análise de dados. Experiência em pesquisa de campo.',
                'beneficios'           => 'Bolsa de pesquisa e participação em seminários.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Ciências Sociais',
                'curso_desejado'       => ['Ciências Econômicas', 'Ciências Sociais', 'Estatística'],
                'remuneracao'          => 700.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(30)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Pesquisa Social Catarinense',
                'projeto_codigo'       => 'SOC-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Nutrição e Dietética',
                'descricao'            => 'Atuação em unidade de alimentação e nutrição (UAN), planejamento de cardápios, controle de qualidade, atendimento nutricional e educação alimentar.',
                'requisitos'           => 'Cursando Nutrição a partir do 6º semestre. Conhecimento em boas práticas de fabricação.',
                'requisitos_desejaveis'=> 'Experiência em UAN ou serviços de saúde. Conhecimento em software de avaliação nutricional.',
                'beneficios'           => 'Vale-transporte, vale-refeição e uniforme.',
                'tipo'                 => 'estagio',
                'area'                 => 'Saúde',
                'curso_desejado'       => ['Nutrição'],
                'remuneracao'          => 900.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(22)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Nutrição Institucional',
                'projeto_codigo'       => 'SAU-2026-020',
            ],
            [
                'titulo'               => 'Estágio em Arquitetura',
                'descricao'            => 'Desenvolvimento de projetos arquitetônicos para ampliação e reforma de instalações institucionais, elaboração de plantas, cortes, fachadas e memorial descritivo.',
                'requisitos'           => 'Cursando Arquitetura e Urbanismo a partir do 5º semestre. Domínio em AutoCAD.',
                'requisitos_desejaveis'=> 'Experiência com Revit ou SketchUp. Interesse em arquitetura educacional.',
                'beneficios'           => 'Vale-transporte e acompanhamento de arquiteto sênior.',
                'tipo'                 => 'estagio',
                'area'                 => 'Arquitetura',
                'curso_desejado'       => ['Arquitetura e Urbanismo'],
                'remuneracao'          => 1200.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(35)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Reforma Sede FAPEU',
                'projeto_codigo'       => 'ARQ-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Fisioterapia',
                'descricao'            => 'Atendimentos supervisionados em clínica de fisioterapia, elaboração de planos terapêuticos, aplicação de recursos fisioterapêuticos e registro em prontuário eletrônico.',
                'requisitos'           => 'Cursando Fisioterapia a partir do 7º semestre. CREFITO provisório.',
                'requisitos_desejaveis'=> 'Interesse em fisioterapia ortopédica ou neurológica.',
                'beneficios'           => 'Vale-transporte e supervisão clínica.',
                'tipo'                 => 'estagio',
                'area'                 => 'Saúde',
                'curso_desejado'       => ['Fisioterapia'],
                'remuneracao'          => 900.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(28)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Clínica de Reabilitação',
                'projeto_codigo'       => 'SAU-2026-030',
            ],

            // --- VAGAS SEM REMUNERAÇÃO / CARGA HORÁRIA VARIADA ---
            [
                'titulo'               => 'Bolsista Voluntário em Extensão Universitária',
                'descricao'            => 'Participação em atividades de extensão junto à comunidade carente, desenvolvendo projetos sociais, culturais e de inclusão digital sem remuneração financeira.',
                'requisitos'           => 'Aberta a qualquer curso de graduação. Comprometimento e disponibilidade.',
                'requisitos_desejaveis'=> 'Experiência com trabalho voluntário ou projetos sociais.',
                'beneficios'           => 'Certificado de horas complementares e carta de recomendação.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Extensão Universitária',
                'curso_desejado'       => null,
                'remuneracao'          => null,
                'carga_horaria'        => 10,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(60)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Projeto Inclusão Digital',
                'projeto_codigo'       => 'EXT-2026-001',
            ],
            [
                'titulo'               => 'Estágio em Engenharia de Produção',
                'descricao'            => 'Análise e melhoria de processos operacionais, mapeamento de fluxos, estudo de tempos e movimentos e apoio à implantação de metodologias de qualidade (Lean, 5S).',
                'requisitos'           => 'Cursando Engenharia de Produção a partir do 5º semestre. Noções de gestão de processos.',
                'requisitos_desejaveis'=> 'Conhecimento em Six Sigma ou Lean Manufacturing. Experiência com ferramentas de análise de dados.',
                'beneficios'           => 'Vale-transporte, vale-refeição e participação em projetos de melhoria contínua.',
                'tipo'                 => 'estagio',
                'area'                 => 'Engenharia',
                'curso_desejado'       => ['Engenharia de Produção', 'Engenharia Mecânica'],
                'remuneracao'          => 1250.00,
                'carga_horaria'        => 30,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(32)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Eficiência Operacional',
                'projeto_codigo'       => 'ENG-2026-020',
            ],
            [
                'titulo'               => 'Analista Jurídico Pleno',
                'descricao'            => 'Análise de contratos, pareceres jurídicos, acompanhamento de processos administrativos e judiciais, e assessoria às áreas internas em matéria de direito administrativo e civil.',
                'requisitos'           => 'Graduação em Direito e OAB ativa. Mínimo 3 anos de experiência em advocacia ou assessoria jurídica.',
                'requisitos_desejaveis'=> 'Especialização em direito administrativo ou do terceiro setor. Inglês intermediário.',
                'beneficios'           => 'Plano de saúde, plano odontológico, vale-refeição, vale-transporte e PLR.',
                'tipo'                 => 'emprego',
                'area'                 => 'Direito',
                'curso_desejado'       => ['Direito'],
                'remuneracao'          => 7500.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(45)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => null,
                'projeto_codigo'       => null,
            ],
            [
                'titulo'               => 'Estágio em Odontologia',
                'descricao'            => 'Atendimento clínico supervisionado em clínica odontológica universitária, com foco em dentística, periodontia e cirurgia oral menor.',
                'requisitos'           => 'Cursando Odontologia a partir do 7º semestre. CRO provisório.',
                'requisitos_desejaveis'=> 'Habilidade clínica comprovada. Interesse em pesquisa odontológica.',
                'beneficios'           => 'Vale-transporte e materiais fornecidos.',
                'tipo'                 => 'estagio',
                'area'                 => 'Saúde',
                'curso_desejado'       => ['Odontologia'],
                'remuneracao'          => 850.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(19)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Clínica Odontológica UFSC',
                'projeto_codigo'       => 'SAU-2026-040',
            ],
            [
                'titulo'               => 'Coordenador de Captação de Recursos',
                'descricao'            => 'Identificação de oportunidades de financiamento, elaboração de propostas para editais de fomento, gestão de relacionamento com agências financiadoras e coordenação da equipe de projetos.',
                'requisitos'           => 'Graduação em qualquer área. Experiência comprovada em captação de recursos e gestão de projetos financiados.',
                'requisitos_desejaveis'=> 'Experiência com FINEP, CNPq, CAPES ou fundações internacionais. MBA em Gestão de Projetos.',
                'beneficios'           => 'Remuneração competitiva, plano de saúde, plano odontológico e bônus por metas.',
                'tipo'                 => 'emprego',
                'area'                 => 'Administração',
                'curso_desejado'       => ['Administração', 'Ciências Econômicas', 'Engenharia de Produção'],
                'remuneracao'          => 9500.00,
                'carga_horaria'        => 40,
                'modalidade'           => 'hibrido',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(55)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Captação e Fomento 2026',
                'projeto_codigo'       => 'ADM-2026-010',
            ],
            [
                'titulo'               => 'Bolsista em Química Analítica',
                'descricao'            => 'Realização de análises químicas em amostras ambientais e industriais, operação de equipamentos de cromatografia (HPLC, GC-MS) e espectrometria.',
                'requisitos'           => 'Cursando Química ou Engenharia Química a partir do 5º semestre. Experiência em laboratório.',
                'requisitos_desejaveis'=> 'Conhecimento em cromatografia e espectroscopia. Inglês para leitura de artigos científicos.',
                'beneficios'           => 'Bolsa de pesquisa, acesso a laboratórios e publicações científicas.',
                'tipo'                 => 'bolsa',
                'area'                 => 'Ciências Exatas',
                'curso_desejado'       => ['Química', 'Engenharia Química'],
                'remuneracao'          => 800.00,
                'carga_horaria'        => 20,
                'modalidade'           => 'presencial',
                'cidade'               => 'Florianópolis',
                'estado'               => 'SC',
                'data_encerramento'    => now()->addDays(27)->toDateString(),
                'status'               => 'ativa',
                'projeto_nome'         => 'Laboratório de Química Ambiental',
                'projeto_codigo'       => 'QUI-2026-001',
            ],
        ];

        foreach ($vagas as $dados) {
            // Idempotente: re-executar o seeder não duplica vagas
            Vaga::updateOrCreate(
                ['titulo' => $dados['titulo']],
                array_merge($dados, [
                    'coordenador_id' => $coordenador?->id,
                    'gestor_id'      => $dados['status'] === 'ativa' ? $gestor?->id : null,
                    'autorizada_em'  => $dados['status'] === 'ativa' ? now() : null,
                    'notificar_email'=> true,
                    'pais'           => 'Brasil',
                ])
            );
        }
    }
}
